<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>vision_node</name>
  <version>0.0.1</version>
  <description>SAM3 비전 파이프라인과 MoveIt 그리기 노드 모음</description>
  <maintainer email="dorong@example.com">dorong</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <!-- <depend>moveit_msgs</depend> -->
  <depend>std_srvs</depend>
  <depend>visualization_msgs</depend>
  <depend>vision_interfaces</depend>
  <!-- <depend>moveit_ros_planning_interface</depend>
  <depend>moveit_visual_tools</depend> -->

  <!-- contour_pixel 타겟(비전 컨테이너)에만 필요. json 관련 의존성은 이제 없음 -->
  <build_depend>libopencv-dev</build_depend>
  <exec_depend>libopencv-dev</exec_depend>

  <!-- sam(파이썬) 실행에 필요 -->
  <exec_depend>rclpy</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
